name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '22.19.0'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm install
      - run: npm run build
